name: Webhook Example
on: [repository_dispatch, push]
jobs:
  build:
    runs-on: [self-hosted, ppx]
    steps:
    - uses: actions/checkout@v2
    
    - name: get information
      run: |
        cd ${{ secrets.SMI_WORKDIR }}
        ls 
        cd ${{ secrets.SMI_BUILDDIR}}
        ls
        
        echo "GITHUB_EVENT_NAME=" $GITHUB_EVENT_NAME
        
        echo "GITHUB_WORKSPACE=" $GITHUB_WORKSPACE
        echo "${{ github.repository }}=" ${{ github.repository }}
        echo "${{ github.token }}=" ${{ github.token }}
        echo "HOME=" $HOME
        echo "GITHUB_REPOSITORY=" $GITHUB_REPOSITORY
        echo "GITHUB_SHA=" $GITHUB_SHA
        echo "GITHUB_REF=" $GITHUB_REF
        
        mkdir -p /tmp/artifact
        cat <<'EOF' > /tmp/artifact/annotations.json
[
  {
    "message": "This is a annotation message",
    "path": "annotations.json",
    "column": { "start": 17, "end": 45 },
    "line": { "start": 3, "end": 3 },
    "level": "notice"
  },
  {
    "message": "This is a annotation group",
    "path": "annotations.json",
    "column": { "start": 3, "end": 4 },
    "line": { "start": 9, "end": 15 },
    "level": "notice"
  },
  {
    "message": "This is a annotation on file outside of changed",
    "path": "LICENSE.md",
    "line": { "start": 1, "end": 1 },
    "level": "warning"
  }
]       
EOF

    - name: Annotate
      uses: Attest/annotations-action@v0.1.0
      with:
        token: ${{ secrets.git_token }}
        input: '/tmp/artifact/annotations.json'
        title: 'Annota        
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: /tmp/artifact/annotations.json
        
    
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: /home/kashino/log/2020-04/SMI_v19_4/build/microbenchmarks/bw_eager_dev/bandwidth_dev0/bandwidth_dev0.aocx
    
    - name: On my_custom_webhook do ABC...
      if: github.event.action == 'my_custom_webhook'
      run: |
        hostname && echo "Hello From my_custom_webhook...doing ABC"
        
    - name: On my_custom_webhook do XYZ...
      if: github.event.action == 'my_custom_webhook_2'
      run: |
        hostname && echo "Hello From my_custom_webhook_2...doing XYZ"
